// src/store/notesSlice.js
import { createSlice, createAsyncThunk } from "@reduxjs/toolkit";
import { db } from "../db";

// Load notes for a candidate
export const loadNotes = createAsyncThunk(
    "notes/load",
    async (candidateId) => {
        return await db.notes.where("candidateId").equals(candidateId).toArray();
    }
);

// MODIFIED: This thunk now adds a note directly to IndexedDB.
export const addNote = createAsyncThunk(
    "notes/add",
    async (note) => {
        // Replaced the 'fetch' call with a direct Dexie add method.
        const id = await db.notes.add(note);
        // Return the full note object including the new ID generated by Dexie
        return { ...note, id };
    }
);

// Update a note
export const updateNote = createAsyncThunk(
    "notes/update",
    async (note) => {
        await db.notes.put(note);
        return note;
    }
);

// Delete a note
export const deleteNote = createAsyncThunk(
    "notes/delete",
    async (id) => {
        await db.notes.delete(id);
        return id;
    }
);

const notesSlice = createSlice({
    name: "notes",
    initialState: {
        list: [],
        status: "idle",
    },
    reducers: {},
    extraReducers: (builder) => {
        builder
            .addCase(loadNotes.pending, (state) => {
                state.status = "loading";
            })
            .addCase(loadNotes.fulfilled, (state, action) => {
                state.status = "succeeded";
                state.list = action.payload;
            })
            .addCase(addNote.fulfilled, (state, action) => {
                state.list.unshift(action.payload);
            })
            .addCase(updateNote.fulfilled, (state, action) => {
                const index = state.list.findIndex((n) => n.id === action.payload.id);
                if (index !== -1) {
                    state.list[index] = action.payload;
                }
            })
            .addCase(deleteNote.fulfilled, (state, action) => {
                state.list = state.list.filter((n) => n.id !== action.payload);
            });
    },
});

export default notesSlice.reducer;